---
title: "About"
---

## Research

My current projects include:

- The effect of vocal effort on the variability of nasal coarticulation ([IAFPA Research Grant](https://www.iafpa.net/about/research-grants/), 2023)
- Talk and identity in the North Korean refugee diaspora (with [Bronwen Evans](https://www.ucl.ac.uk/pals/people/bronwen-evans), [Jieun Song](https://www.jieunsong.com/) & Rakgyun Shin, [UCL Global Engagement Fund](https://www.ucl.ac.uk/global/funding-staff/global-engagement-funds), 2023–24)

## Education

**PhD in Linguistics**, University of York

- Dissertation: Issues of bilingualism in likelihood ratio-based forensic voice comparison
- Supervisors: Paul Foulkes & Vincent Hughes

**MSc in Forensic Speech Science (Distinction)**, University of York

- Dissertation: Double trouble?: The effect of bilingualism on filled pauses and their discriminatory power in forensic voice comparison
- Supervisors: Paul Foulkes & Vincent Hughes

**Bachelor of Laws (Second Class Honours: Division One)**, The University of Hong Kong

## Roles

Treasurer, [UK Linguistics Olympiad](https://www.uklo.org/)

Coordinator, [Speech Science Forum](https://www.ucl.ac.uk/pals/research/speech-hearing-and-phonetic-sciences/speech-science-forum) seminar series, Department of Speech, Hearing and Phonetic Sciences, UCL (2021–2023)

Editor, [York Papers in Linguistics](http://www.york.ac.uk/language/ypl/) (2018–2021)

Organiser, 6th & 7th Postgraduate Academic Researchers in Linguistics at York (PARLAY) Conference (2019, 2021)

Convenor, Forensic Speech Science Research Group, University of York (2018–2021)

PGR Course Representative, Department of Language and Linguistic Science, University of York (2017–2018)

## Memberships

British Association of Academic Phoneticians

International Association for Forensic Phonetics and Acoustics

Linguistics Association of Great Britain