---
title: "Teaching & PhD Supervision"
---

## PhD supervision

### Current

- [Rakgyun Shin](https://research.lancaster-university.uk/en/persons/rak-shin/){target="_blank"} - A sociophonetic ethnography of the North Korean diaspora in London: Negotiating identity through accent (AHRC funded; co-supervised with [Sebastian Muth](https://www.lancaster.ac.uk/social-sciences/people/sebastian-muth))
- [Scarlett Vanroose-Peer](https://research.lancaster-university.uk/en/persons/scarlett-vanroose-peer/){target="_blank"} - Voice-mixing in voice identification: The risk and impact of data contamination in forensic voice analysis (ESRC funded; co-supervised with [George Brown](https://www.lancaster.ac.uk/social-sciences/people/georgina-brown))

### Supervision interests

I am interested in supervising students in the areas of forensic speech science and sociophonetics, and especially welcome proposals in these areas that address issues related to multilingualism and/or take an experimental approach. Within forensic speech science, I am interested in phonetics-centred proposals that concern voice and identity in production and/or perception.

You are welcome to reach out to me for informal enquiries, but you should consult the Lancaster website for [information and guidance on PhD applications and funding](https://www.lancaster.ac.uk/linguistics/phd/){target="_blank"} in the first instance.

## Teaching

I teach undergraduate and postgraduate modules in the areas of phonetics, forensic speech science, sociolinguistics, and quantitative methods. I also supervise BA and MA/MSc dissertations in these areas. In 2025/26, I teach on the following modules:

- LING223 *English Phonetics*
- LING488 *Foundations of Speech Science*
- LING541 *Quantitative Data and Analysis for Applied Linguistics*

I have recently taught on the following modules:

- LING301a *Dissertation Preparation*
- LING429 *Forensic Linguistics*
